### ISSUE TITLE
LAMBS Settings

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/cba-settings-lock#33] opened 2021-03-30 09:40 UTC
@freghar mentioned on Discord that LAMBS settings should be taken a look at. Just opening an issue to keep track of this and maybe implement a change for the next cba file update.

Reference: https://discord.com/channels/154907081256730624/281495773894410240/826046297894420520

**Comment by JamesTheClarke** [comment] 2021-03-30 20:15
I assume you'd recommend to set all the settings mentioned above to "force", correct?

**Comment by Seb105** [comment] 2021-04-03 23:03
Testing by Freghar and I have determined that information sharing between groups is causing all manner of issues 
- It's way too fast. Mere moments after contact starting every unit of the side is aware of the exact position of enemies
- This causes units to shoot with 5.56mm weapons at targets more than 1km away, on the other side of a hill, that they can't even see.
- Units routinely engage targets through terrain i.e shooting at hills
- It causes groups to ignore waypoints and abandon their positions to chase down enemies 1km away
- The above point contributes to the stratification of groups, where group units are ~1km apart.

Look at this shit, which is caused by information sharing: https://priv.carpenoctem.co/cntr/?m=9796511d&t=690

There is also something else causing units to change combat mode but it's not too bad comparitively, the majority of bad behaviour can be fixed by disabling this radio sharing.

If we insist on using LAMBS AI, which at this point I think is worse than vanilla from a realism/fun perspective, I strongly recommend:

`force force lambs_main_radioDisabled = true;`

Or at least have it default to off.

**Comment by freghar** [comment] 2021-04-03 23:10
I think this belongs to the staff forums, not here in this unrelated issue (which is about enforcement only). However I'll add that we tested reducing radio ranges to 20m from 500m (and "backpack radio" from 2km to 500m, lowest possible) without any apparent change, only `radioDisabled` finally helped.

**Comment by JamesTheClarke** [comment] 2021-04-07 09:13
I agree with @freghar that setting `force force lambs_main_radioDisabled = true;` would require a Staff Forum discussion as it disables a core aspect of LAMBS AI permanently for all Mission Makers.

However, I also agree with @Seb105 that Mission Makers should be able to disable information sharing as well as other LAMBS settings if they so choose for their scenario. I did a small localised and server-side test and also struggled to reproduce the same occurrence from last Friday outside of that specific mission.

Thus I'd set all current LAMBS settings to `force` to ensure they are enforced onto all clients but give Mission Makers the option to tweak them further or disable them entirely.

`// LAMBS Danger
force lambs_danger_cqbRange = 60;
force lambs_danger_disableAIAutonomousManoeuvres = false;
force lambs_danger_disableAIDeployStaticWeapons = false;
force lambs_danger_disableAIFindStaticWeapons = false;
force lambs_danger_disableAIHideFromTanksAndAircraft = false;
force lambs_danger_disableAIPlayerGroup = false;
force lambs_danger_disableAIPlayerGroupReaction = false;
force lambs_danger_disableAutonomousFlares = false;
force lambs_danger_panicChance = 0.1;

// LAMBS Danger Eventhandlers
force lambs_eventhandlers_ExplosionEventHandlerEnabled = true;
force lambs_eventhandlers_ExplosionReactionTime = 9;

// LAMBS Danger WP
force lambs_wp_autoAddArtillery = false;

// LAMBS Main
force lambs_main_combatShareRange = 200;
force lambs_main_debug_Drawing = false;
force lambs_main_debug_FSM = false;
force lambs_main_debug_FSM_civ = false;
force lambs_main_debug_functions = false;
force lambs_main_debug_RenderExpectedDestination = false;
force lambs_main_disableAICallouts = false;
force lambs_main_disableAIDodge = false;
force lambs_main_disableAIFleeing = false;
force lambs_main_disableAIGestures = false;
force lambs_main_disablePlayerGroupSuppression = false;
force lambs_main_indoorMove = 0.1;
force lambs_main_maxRevealValue = 1;
force lambs_main_minFriendlySuppressionDistance = 5;
force lambs_main_minSuppressionRange = 25;
force lambs_main_radioBackpack = 2000;
force lambs_main_radioDisabled = false;
force lambs_main_radioEast = 500;
force lambs_main_radioGuer = 500;
force lambs_main_radioShout = 100;
force lambs_main_radioWest = 500;`

**Closed** 2021-04-13 17:18 UTC
Labels: Enhancement
